### ISSUE TITLE
Kernel source for Oneplus 11R CPH2487, 14.0.0.200(EX01)

### ISSUE THREAD

**Issue by Venkat3620** [OnePlusOSS/android_kernel_oneplus_sm8475#2]
@OnePlusOSSAdmin Please release working kernel source code for Oneplus 11R with all requried modules and dts.
I have reached out through oneplusoss mail and in return in got that kernel source will be shortly released. this was almost 1 and a half months ago. Please release kernel as soon as possible.

Version: 5.10.149
OxygenOS build: CPH2487_13.1.0_581(EX01)

**Comment by PIPIPIG233666** [comment]
@OnePlusOSSAdmin why is op9 getting more frequent updates than 10T/11R?

**Comment by PIPIPIG233666** [comment]
@OnePlusOSSAdmin plz, update the camera modules so that it works

**Comment by Venkat3620** [comment]
@OnePlusOSSAdmin Please push android 14 kernel sources with dts and modules.
oneplus 11 already got its kernel source.

build: CPH2487_14.0.0.200(EX01)
Kernel version: 5.10.168

**Comment by Venkat3620** [comment]
@OnePlusOSSAdmin at this point every chipset is getting updates except sm8475.
please push the oos14 sources with necessary drivers and dts.

**Comment by OnePlusOSSAdmin** [comment]
It hase been updated, please check branch oneplus/sm8475_u_14.0.0_oneplus_11r_5g

**Comment by h0we** [comment]
> It hase been updated, please check branch oneplus/sm8475_u_14.0.0_oneplus_11r_5g

please update touchpanel driver for udon

**Comment by OnePlusOSSAdmin** [comment]
> > It hase been updated, please check branch oneplus/sm8475_u_14.0.0_oneplus_11r_5g
> 
> please update touchpanel driver for udon

OK. It will be released with ace 2 code release, then with 11 R code update.

**Comment by Maitreya25** [comment]
> > > It hase been updated, please check branch oneplus/sm8475_u_14.0.0_oneplus_11r_5g
> > 
> > 
> > please update touchpanel driver for udon
> 
> OK. It will be released with ace 2 code release, then with 11 R code update.

Udon is missing synaptics s3910 one which it uses, synaptics_hbp driver is out of date as well and is missing kernel_cost node and some others which can be seen on stock. Please consider updating it

**Comment by OnePlusOSSAdmin** [comment]
> is missing kernel_cost node and some others which can be seen on stock

Could you please provide code location? We'll check with R&D team when festival leave is over.

**Comment by Maitreya25** [comment]
> > is missing kernel_cost node and some others which can be seen on stock
> 
> Could you please provide code location? We'll check with R&D team when festival leave is over.

vendor/oplus/kernel/touchpanel/synaptics_hbp in modules repo
Stock has the new nodes and 8650 is shipping with the updated driver as well - https://github.com/OnePlusOSS/android_kernel_modules_and_devicetree_oneplus_sm8650/blob/oneplus/sm8650_u_14.0.0_oneplus12/vendor/oplus/kernel/touchpanel/synaptics_hbp/touchpanel_proc.c#L931
However, udon - despite stock shipping with said changes does not have it up to date in kernel source.

every issue is in vendor/oplus/kernel/touchpanel/ only and everything else is fine, kindly look into updating that directory

**Comment by OnePlusOSSAdmin** [comment]
@Venkat3620 Could this issue be closed?
@Maitreya25 For code issue about sm8650, please follow up in corresponding repository.
